apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-manager
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: price-manager
  template:
    metadata:
      labels:
        app: price-manager
    spec:
      containers:
      - name: price-manager
        image: kudelich/price_manager:1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8000

