apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: kudelich/app:3.0 
        env:
          - name: DB
            value: "mydb"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "secret"
          - name: DB_HOST
            value: "db"        # Service name for Postgres
          - name: DB_PORT
            value: "5432"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        livenessProbe:
          exec:
            command:  ["pgrep", "python"]
          initialDelaySeconds:  30
          periodSeconds:  10
          failureThreshold: 3

