name: Kubernetes CD

on:
  workflow_dispatch:   # 👈 allows manual trigger in GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deployment script
        run: |
          bash ./scripts/deploy.sh

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.MY_SECRET }}" > ~/.kube/config
