name: Kubernetes CD

on:
  workflow_dispatch:   # 👈 manual trigger in GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.MY_SECRET }}" > ~/.kube/config

      - name: Run deployment script
        run: bash ./scripts/deploy.sh

        