name: Kubernetes CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    validate:
        name: Validate Kubernetes manifests
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.30.0'
            
            - name: Install kubeconform
              run: |
                curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
                tar -xzf kubeconform.tar.gz
                sudo mv kubeconform /usr/local/bin/
            
            - name: Validate manifests with kubeconform
              run: |
                find . -type f -name "*.yaml" -o -name "*.yml" | \
                xargs kubeconform -strict -ignore-missing-schemas



